# This is a basic workflow to help you get started with Actions

name: CI-CD

env:
  EB_PACKAGE_S3_BUCKET: "otus-arch-application-package"
  EB_APPLICATION_NAME: "OtusArch"
  EB_ENV_NAME: "Otusarch-env"
  DEPLOY_PACKAGE_NAME: "otus_arch_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-2"


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
        
